### ISSUE TITLE
Yggdrasil files missing

### ISSUE THREAD

**Issue by SourceDiver42** [Android-Boot-Manager/Scripts#8]
Hi, I noticed that in the commit history, suddenly the yggdrasil.sh scripts and everything related to yggdrasil was deleted at some point. Looking at the commit history, it happened with this commit:

[https://github.com/Android-Boot-Manager/Scripts/commit/b4910b96405ec6cbec579ebeaa2a6930191c3924](https://github.com/Android-Boot-Manager/Scripts/commit/b4910b96405ec6cbec579ebeaa2a6930191c3924)

Were these deletions intentional?

Cheers

**Comment by nift4** [comment]
There still is the sailfish script: https://github.com/Android-Boot-Manager/Scripts/blob/master/add_os/yggdrasil/add_sailfish.sh

Those were deleted because we moved the intended target to Android 10, but Ubuntu Touch requires Android 9. The way forward for Ubuntu Touch would, in my opinion, be to port it to Android 10 (which is very easy considering the closely related and same-CPU yggdrasilx has Android 10-based Ubuntu Touch). The other files were deleted because the rewritten app does not make use of them anymore.

**Comment by nift4** [comment]
On that note, the yggdrasil bootloader does not work properly at the moment, and the Sailfish script does work (with the old bootloader branch), but it needs some manual intervention (which I couldn't fix because I was stuck at getting the bootloader rebased on the new code). Currently, it's on Luka's list to make that work.
If you have more questions and prefer instant messaging, feel free to join:  https://t.me/andbootmgr
